export declare const ALPHABET_KEY = "ABC";
export declare const NUMERIC_KEY = "?123";
export declare const NUMPAD_KEY = "1234";
export declare const SYMBOL_KEY = "=/<";
export declare const DOTCOM_KEY = ".com";
export declare const SPACE_KEY = " ";
export declare const findKey: (n: string) => string[];
export declare const defaultPreset: string[][][];
export declare const numericPreset: string[][][];
export declare const numpadPreset: string[][][];
export declare const symbolPreset: string[][][];
export declare const emailPreset: string[][][];
